name: Build all tools

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Building all tools
        run: |
          chmod +x gcc
          sudo ./gcc > /dev/null
